version: '3'
services:
  hazelcast-input:
    image: hazelcast-example
    environment:
      - HAZELCAST_MODE=INPUT
      - HAZELCAST_MEMBER=hazelcast-monitor
  hazelcast-monitor:
    image: hazelcast-example
    environment:
      - HAZELCAST_MODE=MONITOR
      - HAZELCAST_MEMBER=hazelcast-input
