services:
  hazelcast-input:
    image: hazelcast-example
    environment:
      - HAZELCAST_MODE=INPUT
      - HAZELCAST_MEMBER=hazelcast-input
    networks:
      - hazelcast-net
    ports:
      - "5702:5701"

# antother PC code (Eduardo)
#  eduardo-read:
#    image: hazelcast-example
#    environment:
#      - HAZELCAST_MODE=MONITOR
#      - HAZELCAST_MEMBER=eduardo-read
#    networks:
#      - hazelcast-net
#    ports:
#      - "5703:5701"

networks:
  hazelcast-net:
    driver: bridge
